kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: oracledb-pvc
  labels:
    type: amazonEBS
spec:
  storageClassName: gp2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
