apiVersion: cr.kanister.io/v1alpha1
kind: Blueprint
metadata:
  name: oracle-blueprint
actions:
  backupprehook:
    type: Deployment
    phases:
    - func: KubeTask
      name: makePGCheckPoint
      args:
        image: ajaykangare/oracledb-rman-sidecar
        imagePullPolicy: IfNotPresent
        namespace: "{{ .Deployment.Namespace }}"
        command:
        - bash
        - -o
        - errexit
        - -o
        - pipefail
        - -c
        - |
          echo "Alter Databse begin backup;" |  sqlplus -S sys/Kube#2020@{{ .Deployment.Name }}.{{ .Deployment.Namespace }}.svc.cluster.local:1521/PSTG.localdomain as sysdba
  backupposthook:
    type: Deployment
    phases:
    - func: KubeTask
      name: afterPGBackup
      args:
        image: ajaykangare/oracledb-rman-sidecar
        imagePullPolicy: IfNotPresent
        namespace: "{{ .Deployment.Namespace }}"
        command:
        - bash
        - -o
        - errexit
        - -o
        - pipefail
        - -c
        - |
          echo "Alter Databse end backup;" |  sqlplus -S sys/Kube#2020@{{ .Deployment.Name }}.{{ .Deployment.Namespace }}.svc.cluster.local:1521/PSTG.localdomain as sysdba
