apiVersion: cr.kanister.io/v1alpha1
kind: Blueprint
metadata:
  name: oracle-blueprint
actions:
  backupPrehook:
    type: Deployment
    phases:
    - func: KubeTask
      name: makeCheckPoint
      args:
        image: ajaykangare/oracledb-rman-sidecar
        imagePullPolicy: IfNotPresent
        namespace: "{{ .Deployment.Namespace }}"
        command:
        - bash
        - -o
        - errexit
        - -o
        - pipefail
        - -c
        - |
          printf "Alter system archive log current; \n  Alter Database begin backup;" |  sqlplus -S sys/Kube#2020@{{ .Deployment.Name }}.{{ .Deployment.Namespace }}.svc.cluster.local:1521/PSTG.localdomain as sysdba          
  backupPosthook:
    type: Deployment
    phases:
    - func: KubeTask
      name: afterBackup
      args:
        image: ajaykangare/oracledb-rman-sidecar
        imagePullPolicy: IfNotPresent
        namespace: "{{ .Deployment.Namespace }}"
        command:
        - bash
        - -o
        - errexit
        - -o
        - pipefail
        - -c
        - |
          printf "Alter Database end backup; \n Alter system archive log current;" |  sqlplus -S sys/Kube#2020@{{ .Deployment.Name }}.{{ .Deployment.Namespace }}.svc.cluster.local:1521/PSTG.localdomain as sysdba
  restore:
    type: Deployment
    phases:
    - func: KubeTask
      name: restoreCheckpoint
      args:
        image: ajaykangare/oracledb-rman-sidecar
        imagePullPolicy: IfNotPresent
        namespace: "{{ .Deployment.Namespace }}"
        command:
        - bash
        - -o
        - errexit
        - -o
        - pipefail
        - -c
        - |
          printf "startup mount \n ALTER SESSION SET NLS_DATE_FORMAT = 'MM/DD/YYYY HH24:MI:SS'; \n recover database snapshot time '2020/07/30 10:57:20'; \n alter database open;" | sqlplus -S sys/Kube#2020@{{ .Deployment.Name }}.{{ .Deployment.Namespace }}.svc.cluster.local:1521/PSTG.localdomain as sysdba
