apiVersion: cr.kanister.io/v1alpha1
kind: Blueprint
metadata:
  name: oracle-blueprint
actions:
  backup:
    type: Deployment
    outputArtifacts:
      oracleCloudDump:
        keyValue:
          s3path: "{{ .Phases.dumpToObjectStore.Output.s3path }}"
    phases:
    - func: KubeTask
      name: dumpToObjectStore
      args:
        image: ajaykangare/oracledb-rman-sidecar
        imagePullPolicy: IfNotPresent
        namespace: "{{ .Deployment.Namespace }}"
        command:
        - bash
        - -o
        - errexit
        - -o
        - pipefail
        - -c
        - |
          s3_path="/oracle-backups/{{ .Deployment.Namespace }}/{{ .Deployment.Name }}/{{ toDate "2006-01-02T15:04:05.999999999Z07:00" .Time  | date "2006-01-02T15-04-05" }}/dump.oracle.gz"
          echo 'BACKUP INCREMENTAL LEVEL 0 DATABASE;' > increamentalbackuplevel0.cmd; rman target sys/Kube#2020@oracle12c.oracledb.svc.cluster.local:1521/PSTG.localdomain @increamentalbackuplevel0.cmd | gzip - | kando location push --profile '{{ toJson .Profile }}' --path ${s3_path} -
          kando output s3path ${s3_path}
